# Generated by Django 4.2.10 on 2024-03-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_student_signup_delete_studentsignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'admin_signup',
            },
        ),
        migrations.CreateModel(
            name='Staff_Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'staff_signup',
            },
        ),
        migrations.DeleteModel(
            name='Student_Signup',
        ),
        migrations.RemoveField(
            model_name='userr',
            name='last_login',
        ),
    ]
