# Generated by Django 4.2.10 on 2024-03-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_department_year_alter_admin_signup_id_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_age', models.IntegerField()),
                ('mobile_number', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=255)),
                ('student_address', models.CharField(max_length=255)),
                ('join_date', models.DateField()),
            ],
        ),
    ]
