# Generated by Django 4.2.10 on 2024-03-16 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_student_email_id_alter_student_student_address_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subject',
            table='suject',
        ),
    ]
