# Generated by Django 4.2.10 on 2024-03-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_student_student_age_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
