# Generated by Django 4.2.10 on 2024-03-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_subject_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='year',
            table='year',
        ),
    ]
