# Generated by Django 4.2.10 on 2024-03-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_department_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='section',
            table='section',
        ),
    ]
