# Generated by Django 4.2.10 on 2024-03-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_section_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table=None,
        ),
    ]
