# Generated by Django 4.2.10 on 2024-03-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_department_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
    ]
