# Generated by Django 4.2.10 on 2024-03-17 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0017_alter_department_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_signup',
            name='email',
        ),
        migrations.AddField(
            model_name='admin_signup',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admin_signup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='admin_signup',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
