# Generated by Django 4.2.10 on 2024-03-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_remove_admin_signup_email_admin_signup_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_signup',
            name='email',
            field=models.EmailField(default=None, max_length=255),
        ),
    ]
