# Generated by Django 4.2.10 on 2024-03-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_admin_signup_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_signup',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='admin_signup',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='admin_signup',
            name='password',
            field=models.CharField(max_length=8),
        ),
    ]
