# Generated by Django 4.2.10 on 2024-03-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_rename_user_admin_signup_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_signup',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
