# Generated by Django 4.2.10 on 2024-03-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_alter_admin_signup_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_signup',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='userr',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
