# Generated by Django 4.2.10 on 2024-05-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_admin_attendance_attendancereport_courses_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Admino',
        ),
    ]
