# Generated by Django 4.2.10 on 2024-06-19 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
