# Generated by Django 4.2.10 on 2024-06-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffs',
            options={'managed': False},
        ),
    ]
