# Generated by Django 4.2.10 on 2024-06-20 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_alter_staffs_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staffs',
            table='staff',
        ),
    ]
