# Generated by Django 4.2.10 on 2024-06-20 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_alter_staffs_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='notificationstaff',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='notificationstudent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userr',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='staffs',
            table='staffs',
        ),
    ]
