# Generated by Django 4.2.10 on 2024-06-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_alter_admin_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='admin_signup',
        ),
        migrations.AlterModelTable(
            name='course',
            table='staffs',
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='notificationstaff',
            table='notification_admin',
        ),
        migrations.AlterModelTable(
            name='notificationstudent',
            table='notification_student',
        ),
        migrations.AlterModelTable(
            name='section',
            table='section',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='subject',
        ),
        migrations.AlterModelTable(
            name='userr',
            table='userr',
        ),
        migrations.AlterModelTable(
            name='year',
            table='year',
        ),
    ]
