# Generated by Django 4.2.10 on 2024-07-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_alter_admin_table_alter_course_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('leave_type', models.CharField(max_length=50)),
                ('adjust_faculty', models.ManyToManyField(to='authentication.faculty')),
                ('class_hours', models.ManyToManyField(to='authentication.classhour')),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
