# Generated by Django 4.2.10 on 2024-07-23 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_classhour_faculty_facultyleave_delete_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyleave',
            name='adjust_faculty',
            field=models.ManyToManyField(related_name='adjusted_faculty', to='authentication.faculty'),
        ),
        migrations.AlterField(
            model_name='facultyleave',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('earned', 'Earned Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave')], max_length=50),
        ),
        migrations.AlterField(
            model_name='facultyleave',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.faculty'),
        ),
        migrations.AlterModelTable(
            name='facultyleave',
            table='faculty_leave_details',
        ),
        migrations.AlterModelTable(
            name='notificationstaff',
            table='notification_staff',
        ),
    ]
