# Generated by Django 4.2.10 on 2024-07-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0036_alter_facultyleave_adjust_faculty_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveReportStaff',
        ),
        migrations.DeleteModel(
            name='LeaveReportStudent',
        ),
    ]
