# Generated by Django 4.2.10 on 2024-07-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0037_delete_leavereportstaff_delete_leavereportstudent'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='admin-signup',
        ),
    ]
