# Generated by Django 4.2.10 on 2024-07-24 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0039_counsellor_permissionrequest'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staffs',
            table='authentication_staffs',
        ),
    ]
