# Generated by Django 4.2.10 on 2024-07-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0040_alter_staffs_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='admin',
            table='admin_signup',
        ),
    ]
